name: Build and Test

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - schemas/**

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        step: ['format:check', 'lint:check', 'build', 'test']
    steps:
      - uses: actions/checkout@v3
      - id: node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc |cut -c2-8)
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ needs.node_version.outputs.NODE_VERSION }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn ${{ matrix.step }}
  evolve:
    runs-on: ubuntu-latest
    needs: [build]
    if: (github.ref == 'refs/heads/develop')
    environment: develop
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn build
      - run: |
          SOURCE_CODE_TX_ID=$(yarn evolve)
          echo "::set-output name=source_code_tx_id::$SOURCE_CODE_TX_ID"
        env:
          ARNS_CONTRACT_TX_ID: ${{ vars.ARNS_CONTRACT_TX_ID }}
          JWK: ${{ secrets.JWK }}
      - run: |
          git tag "${{ steps.run_script.outputs.source_code_tx_id }}"
          git push --tags
